SELECT TABLE_NAME 
FROM [Hayatabad-2].INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE'

SELECT TABLE_NAME 
FROM [Hayatabad-2].INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE'


SELECT TABLE_NAME 
FROM Abdara.INFORMATION_SCHEMA.TABLES a
WHERE TABLE_TYPE = 'BASE TABLE'
and a.TABLE_NAME in (SELECT TABLE_NAME 
FROM [Hayatabad-2].INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE')
order by 1